name: Build and Install CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential

      - name: Build proj 
        run: make
        
      - name: Install proj
        run: sudo make install
      - name: verift install
        run: |
          if [ ! -f /usr/local/bin/your_binary ]; then
            echo "Installation failed! :("
            exit 1
          fi 
          echo "Installation succesful :)"
